/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecteprogramaciolmp;

import Auxiliars.MySelectionModel;
import Auxiliars.TextAreaOutputStream;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Arrays;
import java.io.PrintStream;
import java.util.ArrayList;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.*;
/**
 *
 * @author aula
 */
public class pruebaLuis extends javax.swing.JFrame {

    /**
     * Creates new form Interficie
     */
    public pruebaLuis() {
        initComponents();
        main.setVisible(false);
        descartar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        intro = new javax.swing.JPanel();
        numJugadors = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        numMonedes = new javax.swing.JLabel();
        numMonedes2 = new javax.swing.JTextField();
        monedesJug = new javax.swing.JLabel();
        monedesJug2 = new javax.swing.JTextField();
        descartarBoto = new javax.swing.JButton();
        descartar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        _llistaDinamica = new DefaultListModel();
        llista = new JList(_llistaDinamica);
        mainBoto = new javax.swing.JButton();
        missatgeDescartar = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        superior = new javax.swing.JPanel();
        tornJugador = new javax.swing.JLabel();
        opcions = new javax.swing.JPanel();
        consultarCarta = new javax.swing.JButton();
        intercanvi = new javax.swing.JButton();
        accioRol = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        principal = new javax.swing.JPanel();
        accionsLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        stats = new javax.swing.JTextArea();
        cartesTaula = new javax.swing.JPanel();
        cartaT0 = new javax.swing.JLabel();
        cartaT1 = new javax.swing.JLabel();
        cartaT2 = new javax.swing.JLabel();
        cartaT3 = new javax.swing.JLabel();
        cartaT4 = new javax.swing.JLabel();
        cartaT5 = new javax.swing.JLabel();
        cartaT6 = new javax.swing.JLabel();
        cartaT7 = new javax.swing.JLabel();
        intercanviMall = new javax.swing.JLabel();
        cartesJugador = new javax.swing.JPanel();
        carta0 = new javax.swing.JLabel();
        carta1 = new javax.swing.JLabel();
        carta2 = new javax.swing.JLabel();
        botoContinuaConsulta = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mascarade");

        intro.setBackground(new java.awt.Color(255, 255, 204));

        numJugadors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        numJugadors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJugadorsActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de jugadors:");

        numMonedes.setText("Monedes per guanyar:");

        numMonedes2.setColumns(3);
        numMonedes2.setText("13");
        numMonedes2.setToolTipText("");
        numMonedes2.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                //warn();
            }
            public void removeUpdate(DocumentEvent e) {
                //warn();
            }
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                if (!isInteger(numMonedes2.getText()) || Integer.parseInt(numMonedes2.getText())<=0){
                    JOptionPane.showMessageDialog(null,
                        "Error: Please enter number bigger than 0", "Error Massage",
                        JOptionPane.ERROR_MESSAGE);
                    descartarBoto.setEnabled(false);
                }
                else{
                    descartarBoto.setEnabled(true);
                }

            }
        });
        numMonedes2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numMonedes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMonedes2ActionPerformed(evt);
            }
        });

        monedesJug.setText("Monedes per jugador: ");

        monedesJug2.setColumns(3);
        monedesJug2.setText("3");

        descartarBoto.setText("Continua");
        descartarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarBotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introLayout = new javax.swing.GroupLayout(intro);
        intro.setLayout(introLayout);
        introLayout.setHorizontalGroup(
            introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(descartarBoto))
                    .addGroup(introLayout.createSequentialGroup()
                        .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numJugadors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(introLayout.createSequentialGroup()
                                .addComponent(numMonedes, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
                                .addGap(11, 11, 11)))
                        .addGap(257, 257, 257))
                    .addGroup(introLayout.createSequentialGroup()
                        .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monedesJug)
                            .addComponent(monedesJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numMonedes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(1301, Short.MAX_VALUE))))
        );
        introLayout.setVerticalGroup(
            introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numJugadors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(numMonedes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numMonedes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(monedesJug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monedesJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addComponent(descartarBoto))
        );

        /*
        llista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rei", "Reina", "Bisbe", "Viuda", "Buffo", "Bruixa", "Inquisidor", "Camperol", "Trampos", "Espia", "Lladre" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        */

        llista.setSelectionModel(new MySelectionModel(llista,1));
        jScrollPane3.setViewportView(llista);

        mainBoto.setText("Continua");
        mainBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotoActionPerformed(evt);
            }
        });

        missatgeDescartar.setText("Seleccioneu entre tots els jugadors quines cartes voleu descartar (per fer varies seleccions: CTRL + CLICK)");

        javax.swing.GroupLayout descartarLayout = new javax.swing.GroupLayout(descartar);
        descartar.setLayout(descartarLayout);
        descartarLayout.setHorizontalGroup(
            descartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descartarLayout.createSequentialGroup()
                .addGroup(descartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(descartarLayout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(missatgeDescartar))
                    .addGroup(descartarLayout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(mainBoto)))
                .addContainerGap(544, Short.MAX_VALUE))
            .addGroup(descartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(descartarLayout.createSequentialGroup()
                    .addGap(522, 522, 522)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(775, Short.MAX_VALUE)))
        );
        descartarLayout.setVerticalGroup(
            descartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descartarLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(missatgeDescartar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(mainBoto)
                .addGap(278, 278, 278))
            .addGroup(descartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(descartarLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(352, Short.MAX_VALUE)))
        );

        main.setBackground(new java.awt.Color(0, 0, 0));

        superior.setBackground(new java.awt.Color(51, 51, 51));

        tornJugador.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        tornJugador.setForeground(new java.awt.Color(255, 255, 255));
        tornJugador.setText("Jugador N");

        javax.swing.GroupLayout superiorLayout = new javax.swing.GroupLayout(superior);
        superior.setLayout(superiorLayout);
        superiorLayout.setHorizontalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superiorLayout.createSequentialGroup()
                .addGap(532, 532, 532)
                .addComponent(tornJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        superiorLayout.setVerticalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tornJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        opcions.setBackground(new java.awt.Color(51, 51, 51));

        consultarCarta.setText("Consultar carta");
        consultarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCartaActionPerformed(evt);
            }
        });

        intercanvi.setText("Intercanviar carta amb mall");
        intercanvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intercanviActionPerformed(evt);
            }
        });

        accioRol.setText("Accio De Rol");
        accioRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accioRolActionPerformed(evt);
            }
        });

        jButton1.setText("Intercanviar carta amb jugador");

        javax.swing.GroupLayout opcionsLayout = new javax.swing.GroupLayout(opcions);
        opcions.setLayout(opcionsLayout);
        opcionsLayout.setHorizontalGroup(
            opcionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionsLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(consultarCarta)
                .addGap(229, 229, 229)
                .addComponent(intercanvi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(214, 214, 214)
                .addComponent(accioRol)
                .addGap(72, 72, 72))
        );
        opcionsLayout.setVerticalGroup(
            opcionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opcionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarCarta)
                    .addComponent(intercanvi)
                    .addComponent(accioRol)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        principal.setBackground(new java.awt.Color(255, 51, 51));

        accionsLog.setBackground(new java.awt.Color(51, 51, 51));

        log.setColumns(20);
        log.setRows(5);
        log.setText("LOG DE LA PARTIDA");
        jScrollPane1.setViewportView(log);

        stats.setColumns(20);
        stats.setRows(5);
        stats.setText("ESTADISTIQUES DEL JUGADORS");
        jScrollPane2.setViewportView(stats);

        javax.swing.GroupLayout accionsLogLayout = new javax.swing.GroupLayout(accionsLog);
        accionsLog.setLayout(accionsLogLayout);
        accionsLogLayout.setHorizontalGroup(
            accionsLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionsLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accionsLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        accionsLogLayout.setVerticalGroup(
            accionsLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionsLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        cartesTaula.setBackground(new java.awt.Color(0, 0, 102));

        cartaT0.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        cartaT0.addMouseListener(new MouseAdapter()
            {
                public void mouseClicked(MouseEvent e)
                {
                    System.out.println("clicat");
                    Carta aux= _joc.getCartaMall(0);
                    cartaT0.setIcon(new javax.swing.ImageIcon(getClass().getResource(buscarSourceAmbIDCarta(aux.getNom()))));
                    _cartaEscollida= 0;

                }
            });
            cartaT0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

            cartaT1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            cartaT1.addMouseListener(new MouseAdapter()
                {
                    public void mouseClicked(MouseEvent e)
                    {
                        System.out.println("clicat");
                    }
                });
                cartaT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                cartaT2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                cartaT2.addMouseListener(new MouseAdapter()
                    {
                        public void mouseClicked(MouseEvent e)
                        {
                            System.out.println("clicat");
                        }
                    });
                    cartaT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                    cartaT3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                    cartaT3.addMouseListener(new MouseAdapter()
                        {
                            public void mouseClicked(MouseEvent e)
                            {
                                System.out.println("clicat");
                            }
                        });
                        cartaT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                        cartaT4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                        cartaT4.addMouseListener(new MouseAdapter()
                            {
                                public void mouseClicked(MouseEvent e)
                                {
                                    System.out.println("clicat");
                                }
                            });
                            cartaT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                            cartaT5.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                            cartaT5.addMouseListener(new MouseAdapter()
                                {
                                    public void mouseClicked(MouseEvent e)
                                    {
                                        System.out.println("clicat");
                                    }
                                });
                                cartaT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                                cartaT6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                                cartaT6.addMouseListener(new MouseAdapter()
                                    {
                                        public void mouseClicked(MouseEvent e)
                                        {
                                            System.out.println("clicat");
                                        }
                                    });
                                    cartaT6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                                    cartaT7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                                    cartaT7.addMouseListener(new MouseAdapter()
                                        {
                                            public void mouseClicked(MouseEvent e)
                                            {
                                                System.out.println("clicat");
                                            }
                                        });
                                        cartaT7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                                        intercanviMall.setForeground(new java.awt.Color(255, 255, 255));
                                        intercanviMall.setText("SELECCIONA UNA CARTA. NO VEURAS EL ROL");

                                        javax.swing.GroupLayout cartesTaulaLayout = new javax.swing.GroupLayout(cartesTaula);
                                        cartesTaula.setLayout(cartesTaulaLayout);
                                        cartesTaulaLayout.setHorizontalGroup(
                                            cartesTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(cartesTaulaLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(cartesTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(cartesTaulaLayout.createSequentialGroup()
                                                        .addComponent(cartaT4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cartaT5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(cartesTaulaLayout.createSequentialGroup()
                                                        .addComponent(cartaT0, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cartaT1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(intercanviMall)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(cartesTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(cartesTaulaLayout.createSequentialGroup()
                                                        .addComponent(cartaT6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cartaT7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(cartesTaulaLayout.createSequentialGroup()
                                                        .addComponent(cartaT2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cartaT3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(66, 78, Short.MAX_VALUE))
                                        );
                                        cartesTaulaLayout.setVerticalGroup(
                                            cartesTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(cartesTaulaLayout.createSequentialGroup()
                                                .addContainerGap(16, Short.MAX_VALUE)
                                                .addGroup(cartesTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartesTaulaLayout.createSequentialGroup()
                                                        .addGroup(cartesTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cartaT1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cartaT0, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cartaT2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cartaT3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(cartesTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(cartaT5, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cartaT4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cartaT6, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cartaT7, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addContainerGap())
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartesTaulaLayout.createSequentialGroup()
                                                        .addComponent(intercanviMall, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(300, 300, 300))))
                                        );

                                        cartesJugador.setBackground(new java.awt.Color(51, 51, 51));

                                        carta0.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                                        carta0.addMouseListener(new MouseAdapter()
                                            {
                                                public void mouseClicked(MouseEvent e)
                                                {
                                                    Carta aux= _joc.getCartaJugador(_joc.getIndexJugadorExecutador(0), 0);
                                                    carta0.setIcon(new javax.swing.ImageIcon(getClass().getResource(buscarSourceAmbIDCarta(aux.getNom()))));
                                                    botoContinuaConsulta.setVisible(true);
                                                    carta1.setVisible(false);
                                                    carta2.setVisible(false);
                                                }
                                            });
                                            carta0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                                            carta1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                                            carta1.addMouseListener(new MouseAdapter()
                                                {
                                                    public void mouseClicked(MouseEvent e)
                                                    {
                                                        Carta aux= _joc.getCartaJugador(_joc.getIndexJugadorExecutador(0), 1);
                                                        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource(buscarSourceAmbIDCarta(aux.getNom()))));
                                                        botoContinuaConsulta.setVisible(true);
                                                        carta0.setVisible(false);
                                                        carta2.setVisible(false);
                                                    }
                                                });
                                                carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                                                carta2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                                                carta2.addMouseListener(new MouseAdapter()
                                                    {
                                                        public void mouseClicked(MouseEvent e)
                                                        {
                                                            Carta aux= _joc.getCartaJugador(_joc.getIndexJugadorExecutador(0), 2);
                                                            carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource(buscarSourceAmbIDCarta(aux.getNom()))));
                                                            botoContinuaConsulta.setVisible(true);
                                                            carta1.setVisible(false);
                                                            carta0.setVisible(false);
                                                        }
                                                    });
                                                    carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N

                                                    botoContinuaConsulta.setText("Continua");
                                                    botoContinuaConsulta.addActionListener(new java.awt.event.ActionListener() {
                                                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                            botoContinuaConsultaActionPerformed(evt);
                                                        }
                                                    });

                                                    javax.swing.GroupLayout cartesJugadorLayout = new javax.swing.GroupLayout(cartesJugador);
                                                    cartesJugador.setLayout(cartesJugadorLayout);
                                                    cartesJugadorLayout.setHorizontalGroup(
                                                        cartesJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(cartesJugadorLayout.createSequentialGroup()
                                                            .addGap(82, 82, 82)
                                                            .addComponent(carta0)
                                                            .addGap(78, 78, 78)
                                                            .addComponent(carta1)
                                                            .addGap(75, 75, 75)
                                                            .addComponent(carta2)
                                                            .addContainerGap(112, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartesJugadorLayout.createSequentialGroup()
                                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(botoContinuaConsulta)
                                                            .addGap(406, 406, 406))
                                                    );
                                                    cartesJugadorLayout.setVerticalGroup(
                                                        cartesJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(cartesJugadorLayout.createSequentialGroup()
                                                            .addGap(89, 89, 89)
                                                            .addGroup(cartesJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(carta2)
                                                                .addComponent(carta1)
                                                                .addComponent(carta0))
                                                            .addGap(57, 57, 57)
                                                            .addComponent(botoContinuaConsulta)
                                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    );

                                                    javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
                                                    principal.setLayout(principalLayout);
                                                    principalLayout.setHorizontalGroup(
                                                        principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                                                            .addContainerGap()
                                                            .addComponent(accionsLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(cartesJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addContainerGap())
                                                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(principalLayout.createSequentialGroup()
                                                                .addGap(301, 301, 301)
                                                                .addComponent(cartesTaula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addContainerGap()))
                                                    );
                                                    principalLayout.setVerticalGroup(
                                                        principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                                                            .addContainerGap()
                                                            .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(accionsLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(cartesJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addContainerGap())
                                                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(principalLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(cartesTaula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addContainerGap()))
                                                    );

                                                    javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
                                                    main.setLayout(mainLayout);
                                                    mainLayout.setHorizontalGroup(
                                                        mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(opcions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(superior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    );
                                                    mainLayout.setVerticalGroup(
                                                        mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(mainLayout.createSequentialGroup()
                                                            .addComponent(superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(opcions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    );

                                                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                                                    getContentPane().setLayout(layout);
                                                    layout.setHorizontalGroup(
                                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(intro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(descartar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    );
                                                    layout.setVerticalGroup(
                                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(intro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addContainerGap())
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(descartar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    );

                                                    pack();
                                                }// </editor-fold>//GEN-END:initComponents

    private void numJugadorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numJugadorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numJugadorsActionPerformed

    private void numMonedes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMonedes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMonedes2ActionPerformed

    private void descartarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarBotoActionPerformed
        
        
        setAdreces();
        
        int nombreDeJugadors= numJugadors.getSelectedIndex() + 2;
        int nombreDeMonedesPerGuanyar= Integer.parseInt(numMonedes2.getText());
        int nombreDeMonedesPerJugador= Integer.parseInt(monedesJug2.getText());
        
        //REDIRIGEIX LA SORTIDA A JTEXT
        PrintStream out = new PrintStream(new TextAreaOutputStream(log));
        System.setOut(out);
        System.setErr(out);
        log.setText(Integer.toString(nombreDeJugadors));
        
        //CREA PARTIDA
        _joc= new Partida(nombreDeJugadors,nombreDeMonedesPerGuanyar,nombreDeMonedesPerJugador);
        tornJugador.setText("Jugador "+_joc.getIndexCorregit(0));
        _joc.descartarCartesAUTO();
        
        //AGREGO A LA LLISTA GUI ELS ROLS QUE NO S'HAN DESCARTAT AUTOMATICAMENT
        String [] cartesSenseDescartar= _joc.getCartesNoDescartadesGUI();
        for(int i=0; i<cartesSenseDescartar.length;i++){
            _llistaDinamica.addElement(cartesSenseDescartar[i]);
        }
        //CONFIGURO LES SELECCIONS DE LA LLISTA
        int minim= _joc.getNumJugadors();
        int limit= _joc.getMallSize();
        if(minim<4){
            limit= limit-7;
        }
        else{
            limit= limit - minim - 1;
        }
        
        llista.setSelectionModel(new MySelectionModel(llista,limit));
        
        //ENTRO A LA VENTANA DE DESCARTAR
        intro.setVisible(false);
        descartar.setVisible(true);
        
        
        //pel canal de sortida els elements seleccionats.
        //System.out.println(Arrays.toString(seleccionatsDescartar.toArray()));
        
        //
    }//GEN-LAST:event_descartarBotoActionPerformed

    private void consultarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCartaActionPerformed
        // TODO add your handling code here:
        cartesJugador.setVisible(true);
        cartesTaula.setVisible(false);
        botoContinuaConsulta.setVisible(false);
        if(_joc.getNumJugadors()>3){//MOSTRO NOMES UNA CARTA
            carta0.setVisible(true);
            carta1.setVisible(false);
            carta2.setVisible(false);
        }
        else if(_joc.getNumJugadors()==3){//MOSTRO DUES CARTES
            carta0.setVisible(true);
            carta1.setVisible(true);
            carta2.setVisible(false);
        }
        else{//HI HA DOS JUGADORS I PER TANT MOSTRO TOTES TRES
            carta0.setVisible(true);
            carta1.setVisible(true);
            carta2.setVisible(true);
        }
        _joc.mostrarCartaJugadorActual(0);//de moment fico la primera o unica carta
        opcions.setVisible(false);
    }//GEN-LAST:event_consultarCartaActionPerformed
    
    
    private void accioRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accioRolActionPerformed
        // TODO add your handling code here:
        //principal.setVisible(false);
        
    }//GEN-LAST:event_accioRolActionPerformed

    private void mainBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotoActionPerformed
        //OBTINC ELS ROLS SELECCIONATS PER SER DESCARTATS
        List<String> seleccionatsDescartar= llista.getSelectedValuesList();
        _joc.descartarCartes(seleccionatsDescartar);
        
        _joc.iniciPartidaGUI();
        
        descartar.setVisible(false);
        main.setVisible(true);
        cartesJugador.setVisible(false);
        cartesTaula.setVisible(false);
        //DESCARTAR CARTES AQUI
    }//GEN-LAST:event_mainBotoActionPerformed

    private void botoContinuaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoContinuaConsultaActionPerformed
        cartesJugador.setVisible(false);
        carta0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N
        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N
        carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/P_revers.jpg"))); // NOI18N
        opcions.setVisible(true);
        //AUMENTAR EL TURNO
        _joc.actualitzaTorn();
        tornJugador.setText("Jugador "+_joc.getIndexJugadorExecutador(0));
    }//GEN-LAST:event_botoContinuaConsultaActionPerformed

    private void intercanviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intercanviActionPerformed
        cartesJugador.setVisible(false);
        cartesTaula.setVisible(true);
        opcions.setVisible(false);
    }//GEN-LAST:event_intercanviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static boolean isInteger(String s) {
        return isInteger(s,10);
    }

    public static boolean isInteger(String s, int radix) {
        if(s.isEmpty()) return false;
        for(int i = 0; i < s.length(); i++) {
            if(i == 0 && s.charAt(i) == '-') {
                if(s.length() == 1) return false;
                else continue;
            }
            if(Character.digit(s.charAt(i),radix) < 0) return false;
        }
        return true;
    }
    
    public void setAdreces(){
        _id = new ArrayList<>(Arrays.asList(
                "Jutge",
                "Reina",
                "Rei",
                "Bisbe",
                "Viuda",
                "Buffo",
                "Bruixa",
                "Inquisidor",
                "Camperol",
                "Trampos",
                "Espia",
                "Lladre" 
        ));
        _adreces = new ArrayList<>(Arrays.asList(
                "/resources/P_jutge.jpg",
                "/resources/P_reina.jpg",
                "/resources/P_rei.jpg",
                "/resources/P_bisbe.jpg",
                "/resources/P_viuda.jpg",
                "/resources/P_buffo.jpg",
                "/resources/P_bruixa.jpg",
                "/resources/P_inquisidor.jpg",
                "/resources/P_camperol.jpg",
                "/resources/P_trampos.jpg",
                "/resources/P_espia.jpg",
                "/resources/P_lladre.jpg" 
        ));
    }
    private String buscarSourceAmbIDCarta(String idCarta){
        int index= _id.indexOf(idCarta);
        return _adreces.get(index);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebaLuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebaLuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebaLuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebaLuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebaLuis().setVisible(true);
                //consulta.setVisible(false);
                
            }
        });
        
    }
    //PER FICAR LES IMATGES CORRESPONENTS
    private ArrayList<String> _id;
    private ArrayList<String> _adreces;
    
    //PER FER LA LLISTA DINAMICA
    private DefaultListModel _llistaDinamica;
    
    //PARTIDA
    private Partida _joc;
    
    //VARIABLES PARTIDA
    int _cartaEscollida; //de moment feta servir al intercanvi amb mall
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accioRol;
    private javax.swing.JPanel accionsLog;
    private javax.swing.JButton botoContinuaConsulta;
    private javax.swing.JLabel carta0;
    private javax.swing.JLabel carta1;
    private javax.swing.JLabel carta2;
    private javax.swing.JLabel cartaT0;
    private javax.swing.JLabel cartaT1;
    private javax.swing.JLabel cartaT2;
    private javax.swing.JLabel cartaT3;
    private javax.swing.JLabel cartaT4;
    private javax.swing.JLabel cartaT5;
    private javax.swing.JLabel cartaT6;
    private javax.swing.JLabel cartaT7;
    private javax.swing.JPanel cartesJugador;
    private javax.swing.JPanel cartesTaula;
    private javax.swing.JButton consultarCarta;
    private javax.swing.JPanel descartar;
    private javax.swing.JButton descartarBoto;
    private javax.swing.JButton intercanvi;
    private javax.swing.JLabel intercanviMall;
    private javax.swing.JPanel intro;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> llista;
    private javax.swing.JTextArea log;
    private javax.swing.JPanel main;
    private javax.swing.JButton mainBoto;
    private javax.swing.JLabel missatgeDescartar;
    private javax.swing.JLabel monedesJug;
    private javax.swing.JTextField monedesJug2;
    private javax.swing.JComboBox numJugadors;
    private javax.swing.JLabel numMonedes;
    private javax.swing.JTextField numMonedes2;
    private javax.swing.JPanel opcions;
    private javax.swing.JPanel principal;
    private javax.swing.JTextArea stats;
    private javax.swing.JPanel superior;
    private javax.swing.JLabel tornJugador;
    // End of variables declaration//GEN-END:variables
}
