/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecteprogramaciolmp;

import TextAreaOutputStream.TextAreaOutputStream;
import java.util.List;
import java.util.Arrays;
import java.io.PrintStream;
/**
 *
 * @author aula
 */
public class pruebaLuis extends javax.swing.JFrame {

    /**
     * Creates new form Interficie
     */
    public pruebaLuis() {
        initComponents();
        main.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        intro = new javax.swing.JPanel();
        numJugadors = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        numMonedes = new javax.swing.JLabel();
        numMonedes2 = new javax.swing.JTextField();
        monedesJug = new javax.swing.JLabel();
        monedesJug2 = new javax.swing.JTextField();
        mainBoto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        llista = new javax.swing.JList<>();
        main = new javax.swing.JPanel();
        superior = new javax.swing.JPanel();
        tornJugador = new javax.swing.JLabel();
        opcions = new javax.swing.JPanel();
        consultarCarta = new javax.swing.JButton();
        intercanvi = new javax.swing.JButton();
        accioRol = new javax.swing.JButton();
        principal = new javax.swing.JPanel();
        accionsLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        stats = new javax.swing.JTextArea();
        cartes = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        intro.setBackground(new java.awt.Color(255, 255, 204));

        numJugadors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        numJugadors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJugadorsActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de jugadors:");

        numMonedes.setText("Monedes per guanyar:");

        numMonedes2.setText("jTextField1");
        numMonedes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMonedes2ActionPerformed(evt);
            }
        });

        monedesJug.setText("Monedes per jugador: ");

        monedesJug2.setText("jTextField2");

        mainBoto.setText("Next");
        mainBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotoActionPerformed(evt);
            }
        });

        llista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rei", "Reina", "Bisbe", "Jutge", "Camperols", "Inquisidor", "Viuda", "Espia", "Lladre", "Trampos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(llista);

        javax.swing.GroupLayout introLayout = new javax.swing.GroupLayout(intro);
        intro.setLayout(introLayout);
        introLayout.setHorizontalGroup(
            introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mainBoto))
                    .addGroup(introLayout.createSequentialGroup()
                        .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(introLayout.createSequentialGroup()
                                .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numJugadors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(introLayout.createSequentialGroup()
                                        .addComponent(numMonedes, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                                        .addGap(11, 11, 11)))
                                .addGap(124, 124, 124))
                            .addGroup(introLayout.createSequentialGroup()
                                .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monedesJug)
                                    .addComponent(monedesJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numMonedes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        introLayout.setVerticalGroup(
            introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numJugadors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(introLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(numMonedes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numMonedes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(monedesJug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monedesJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(introLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(mainBoto))
        );

        main.setBackground(new java.awt.Color(0, 0, 0));

        superior.setBackground(new java.awt.Color(255, 153, 255));

        tornJugador.setText("Jugador N");

        javax.swing.GroupLayout superiorLayout = new javax.swing.GroupLayout(superior);
        superior.setLayout(superiorLayout);
        superiorLayout.setHorizontalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tornJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(491, 491, 491))
        );
        superiorLayout.setVerticalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tornJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        opcions.setBackground(new java.awt.Color(255, 255, 51));

        consultarCarta.setText("Consultar carta");
        consultarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCartaActionPerformed(evt);
            }
        });

        intercanvi.setText("Intercanviar amb mall");

        accioRol.setText("Accio De Rol");
        accioRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accioRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionsLayout = new javax.swing.GroupLayout(opcions);
        opcions.setLayout(opcionsLayout);
        opcionsLayout.setHorizontalGroup(
            opcionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionsLayout.createSequentialGroup()
                .addComponent(consultarCarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(intercanvi)
                .addGap(357, 357, 357)
                .addComponent(accioRol))
        );
        opcionsLayout.setVerticalGroup(
            opcionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opcionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarCarta)
                    .addComponent(intercanvi)
                    .addComponent(accioRol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        principal.setBackground(new java.awt.Color(204, 255, 255));

        accionsLog.setBackground(new java.awt.Color(204, 255, 204));

        log.setColumns(20);
        log.setRows(5);
        log.setText("LOG DE LA PARTIDA");
        jScrollPane1.setViewportView(log);

        stats.setColumns(20);
        stats.setRows(5);
        stats.setText("ESTADISTIQUES DEL JUGADORS");
        jScrollPane2.setViewportView(stats);

        javax.swing.GroupLayout accionsLogLayout = new javax.swing.GroupLayout(accionsLog);
        accionsLog.setLayout(accionsLogLayout);
        accionsLogLayout.setHorizontalGroup(
            accionsLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionsLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accionsLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accionsLogLayout.setVerticalGroup(
            accionsLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionsLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        cartes.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout cartesLayout = new javax.swing.GroupLayout(cartes);
        cartes.setLayout(cartesLayout);
        cartesLayout.setHorizontalGroup(
            cartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );
        cartesLayout.setVerticalGroup(
            cartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accionsLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accionsLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cartes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(opcions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(intro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numJugadorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numJugadorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numJugadorsActionPerformed

    private void numMonedes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMonedes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMonedes2ActionPerformed

    private void mainBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotoActionPerformed
        intro.setVisible(false);
        main.setVisible(true);
        int nombreDeJugadors= numJugadors.getSelectedIndex() + 2;
        int nombreDeMonedesPerGuanyar= Integer.parseInt(numMonedes2.getText());
        int nombreDeMonedesPerJugador= Integer.parseInt(monedesJug2.getText());
        
        //REDIRIGEIX LA SORTIDA A JTEXT
        PrintStream out = new PrintStream(new TextAreaOutputStream(log));
        System.setOut(out);
        System.setErr(out);
        log.setText(Integer.toString(nombreDeJugadors));
        
        //guardo els rols seleccionats.
        List<String> seleccionatsDescartar= llista.getSelectedValuesList();
        
        
        //INICIALITZA PARTIDA
        p= new Partida(nombreDeJugadors,nombreDeMonedesPerGuanyar,nombreDeMonedesPerJugador);
        tornJugador.setText("Jugador "+p.getIndexCorregit(0));
        
        //pel canal de sortida els elements seleccionats.
        System.out.println(Arrays.toString(seleccionatsDescartar.toArray()));
        
        p.mostraEstadistiques();
    }//GEN-LAST:event_mainBotoActionPerformed

    private void consultarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCartaActionPerformed
        // TODO add your handling code here:
        
        /*intro.setVisible(true);
        main.setVisible(false);*/
        
        
    }//GEN-LAST:event_consultarCartaActionPerformed

    private void accioRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accioRolActionPerformed
        // TODO add your handling code here:
        //principal.setVisible(false);
        
    }//GEN-LAST:event_accioRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebaLuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebaLuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebaLuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebaLuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebaLuis().setVisible(true);
                //consulta.setVisible(false);
                
            }
        });
        
    }
    private Partida p;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accioRol;
    private javax.swing.JPanel accionsLog;
    private javax.swing.JPanel cartes;
    private javax.swing.JButton consultarCarta;
    private javax.swing.JButton intercanvi;
    private javax.swing.JPanel intro;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> llista;
    private javax.swing.JTextArea log;
    private javax.swing.JPanel main;
    private javax.swing.JButton mainBoto;
    private javax.swing.JLabel monedesJug;
    private javax.swing.JTextField monedesJug2;
    private javax.swing.JComboBox numJugadors;
    private javax.swing.JLabel numMonedes;
    private javax.swing.JTextField numMonedes2;
    private javax.swing.JPanel opcions;
    private javax.swing.JPanel principal;
    private javax.swing.JTextArea stats;
    private javax.swing.JPanel superior;
    private javax.swing.JLabel tornJugador;
    // End of variables declaration//GEN-END:variables
}
